[package]
name = "cruct_shared"
version = "0.1.0"
edition = "2024"

[dependencies]
thiserror = "2.0.12"

toml = { version = "0.8.20", default-features = false, features = [
    "parse",
    "display",
] } # Parsers
jzon = "0.12.5"
yaml-rust2 = "0.10.1"
