[package]
name = "cruct_shared"
version = "0.1.0"
edition = "2024"

[dependencies]
thiserror = "2.0.12"

# Parsers
jzon = "0.12.5"
toml_edit = "0.22.24"
yaml-rust2 = "0.10.1"

[dev-dependencies]
tempfile = "3.19.1"
